<?php

/* DO NOT EDIT THIS FILE */

class MainController 
{

	protected $view;
	protected $variables;
	public function __construct()
	{
		$this->variables = array();
	}
	public function renderView($view, $variables=array())
	{
		foreach ($variables as $var_name=>$value)
		{	
			$$var_name = $value;
		}
		if (file_exists("../app/views/$view.php"))
		{
			ob_start();
			include "../app/views/$view.php";
			$file_contents = ob_get_contents();
			ob_end_clean();

			// Parse the file for blade-esque terms
			$file_contents = str_replace('}}', ';?>', $file_contents);
			$file_contents = str_replace('{{', '<?=', $file_contents);
			file_put_contents("../cache/tmp/temp.php", $file_contents);
			include "../cache/tmp/temp.php";
		}
		else {
			// Enter your view not found page here...
			echo 'View not found';
			die();
		}
	}
	public function redirect($controllerAction)
	{

		global $route;
		include "../index.php";
		// Find the Route associated with the Controller
		$url = WEBROOT.$route->searchByControllerAction($controllerAction);

		header("location: $url");
		/*
		$controllerAction = explode('@', $controllerAction);
		$controller = $controllerAction[0];
		$action = $controllerAction[1];
		if (class_exists($controller))
		{
			$controller = new $controller;
			$controller->$action();
		}
		else {
			include "../app/controllers/$controller.php";
			$controller = new $controller;
			$controller->$action();
		}
		*/

	}
}